# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Clearpaste < Formula
  desc "Auto-clean terminal formatting artifacts from clipboard"
  homepage "https://github.com/tonytangdev/clearpaste"
  version "0.1.0"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/tonytangdev/clearpaste/releases/download/v0.1.0/clearpaste_0.1.0_darwin_amd64.tar.gz"
    sha256 "f73287b288191edb8b85eb0b06989aaa1cbc04094de6edad61c72ec260b9de92"

    define_method(:install) do
      bin.install "clearpaste"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/tonytangdev/clearpaste/releases/download/v0.1.0/clearpaste_0.1.0_darwin_arm64.tar.gz"
    sha256 "2701aeef50df8e5ee6e34bc44651ec04d21ff6cb156e446bf8943033521db785"

    define_method(:install) do
      bin.install "clearpaste"
    end
  end
end
